# Generated by Django 5.1.3 on 2024-11-25 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('telephone', models.TextField()),
                ('email', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('gps_coordinates', models.CharField(max_length=255, null=True)),
                ('farm_size', models.FloatField()),
                ('description', models.TextField()),
                ('growth_stage', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('production', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrot_Practice',
            fields=[
                ('practice_id', models.AutoField(primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.AutoField(primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=255)),
                ('gps_coordinates', models.CharField(max_length=255)),
                ('area_size', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disease_Detection',
            fields=[
                ('detection_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_type', models.CharField(max_length=100)),
                ('detection_date', models.DateField()),
                ('recommendation', models.TextField()),
                ('detection_status', models.CharField(max_length=50)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='Webapp.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='farmer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='Webapp.farmer'),
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('harvest_id', models.AutoField(primary_key=True, serialize=False)),
                ('harvest_date', models.DateField()),
                ('quantity', models.FloatField()),
                ('quality_rating', models.IntegerField()),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='Webapp.farm')),
            ],
        ),
        migrations.CreateModel(
            name='AI_Harvest_Sorting',
            fields=[
                ('sorting_id', models.AutoField(primary_key=True, serialize=False)),
                ('quality_score', models.FloatField()),
                ('sorted_date', models.DateField()),
                ('selected_for_export', models.BooleanField(default=False)),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortings', to='Webapp.harvest')),
            ],
        ),
        migrations.CreateModel(
            name='Smart_Irrigation',
            fields=[
                ('irrigation_id', models.AutoField(primary_key=True, serialize=False)),
                ('water_usage', models.FloatField()),
                ('irrigation_date', models.DateField()),
                ('soil_moisture_level', models.FloatField()),
                ('sensor_status', models.CharField(max_length=50)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigations', to='Webapp.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.FloatField()),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='Webapp.farm')),
            ],
        ),
        migrations.CreateModel(
            name='IoT_Monitoring',
            fields=[
                ('monitoring_id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('monitoring_date', models.DateField()),
                ('alert_status', models.CharField(max_length=50)),
                ('storage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorings', to='Webapp.storage')),
            ],
        ),
    ]
