# Generated by Django 5.1.3 on 2024-11-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_application_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='farmer_id',
            new_name='farmer',
        ),
    ]
