# Generated by Django 5.1.3 on 2024-11-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0005_rename_farmer_id_farm_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegatable_Practice',
            fields=[
                ('practice_id', models.AutoField(primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('Vegetable_type', models.CharField(default='Carrot', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Carrot_Practice',
        ),
        migrations.AddField(
            model_name='ai_harvest_sorting',
            name='Vegetable_type',
            field=models.CharField(default='Carrot', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='Vegetable_type',
            field=models.CharField(default='Carrot', max_length=20),
        ),
        migrations.AddField(
            model_name='disease_detection',
            name='Vegetable_type',
            field=models.CharField(default='Carrot', max_length=20),
        ),
        migrations.AddField(
            model_name='farm',
            name='Vegetable_type',
            field=models.CharField(default='Carrot', max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='Vegetable_type',
            field=models.CharField(default='Carrot', max_length=20),
        ),
        migrations.AddField(
            model_name='harvest',
            name='Vegetable_type',
            field=models.CharField(default='Carrot', max_length=20),
        ),
        migrations.AddField(
            model_name='iot_monitoring',
            name='Vegetable_type',
            field=models.CharField(default='Carrot', max_length=20),
        ),
        migrations.AddField(
            model_name='smart_irrigation',
            name='Vegetable_type',
            field=models.CharField(default='Carrot', max_length=20),
        ),
        migrations.AddField(
            model_name='storage',
            name='Vegetable_type',
            field=models.CharField(default='Carrot', max_length=20),
        ),
    ]
