# Generated by Django 5.1.3 on 2024-11-29 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_vegatable_practice_delete_carrot_practice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vegatable_practice',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='carrot', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
