# Generated by Django 5.1.3 on 2024-11-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0008_alter_vegatable_practice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegatable_practice',
            name='user',
        ),
    ]
