# Generated by Django 5.1.3 on 2024-11-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0010_vegatable_practice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='farm_image',
            field=models.ImageField(default='th1.jpeg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_image',
            field=models.ImageField(default='th1.jpeg', null=True, upload_to=''),
        ),
    ]
