# Generated by Django 5.1.3 on 2024-12-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0014_alter_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='gps_coordinates',
        ),
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(default=-1.9441),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.FloatField(default=30.0619),
        ),
    ]
